name: animations
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-174.3.beta <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter

  flutter_animate: ^4.5.0
  font_awesome_flutter: ^10.7.0
  like_button: ^2.0.5
  vector_math: ^2.1.4
  widgetbook: ^3.7.0
  widgetbook_annotation: ^3.1.0  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  widgetbook_generator: ^3.7.0

flutter:
  uses-material-design: true
